### ISSUE TITLE
Regulated Ontology Terms not Colored

### ISSUE THREAD

**Issue by hcadre** [csmc-vaneykjlab/pine#18]
Dear Developers, 
Thank you very much for this very helpful tool! 
There occurs one glitch though, which occurs reproducibly when it comes to the proper coloring of the Ontology Network - regulated terms are not colored accordingly and therefore it is not clear, which ones are up - and downregulated, respectively. E.g. 100% of the genes in my query that are associated with the term "regulation of DNA-templated transcription, elongation" are downregulated:
![image](https://user-images.githubusercontent.com/16349515/156758891-d35aa7b7-1989-48af-b726-9329c32edf3a.png)
Yet, in the heatmap of the network the term appears as being not regulated:
![image](https://user-images.githubusercontent.com/16349515/156759013-da0fb1f2-5688-4d4c-9bf1-b68cc2ee458b.png)
Is this an issue of inappropriate mapping in cytoscape?
Any idea or suggestion on how to proceed?

**Comment by Niveda-S** [comment]
Hi! At this point, we do not show regulation of the term because there are multiple "Comparison" labels which need to be represented.
For example, in your case, the 100% downregulation for the term "regulation of DNA-templated transcription, elongation" is specifically only for the comparison label you see on the PINE UI: "S1P5min-DMSO". If you click the dropdown for the "Comparison", you will see your other labels also present. Selecting a different comparison label will update the %changed to show the overall up or downregulation of that term for the particular label. 
Since there are multiple comparisons based on which the term, we thought it be confusing to represent the term as a heatmap as well. So, this feature of the term being given a color depicting up and down regulation is only available in the single fold change analysis option in PINE. In case of multi fold change analysis, only the sites are colored based on fold change provided

**Comment by hcadre** [comment]
Thank you very much for the clarification! :-)
